language: android
sudo: required
dist: precise
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - android-update-sdk --components=tools
  - android-update-sdk --components=platform-tools
  - android-update-sdk --components=build-tools-27.0.3
  - android-update-sdk --components=android-24
  - android-update-sdk --components=android-27
  - android-update-sdk --components=extra-android-m2repository

stages:
  - Unit test
  - Integration test

jobs:
  include:
    # Unit Test
    - stage:          Unit test
      env:            module=ai
      script:         ./gradlew $module:test

    - stage:          Unit test
      env:            module=app
      script:         ./gradlew $module:test

    # Integration Test
    - stage:          Integration test
      env:            ❤ = armeabi-v7a-android-24
      install:
        - android-update-sdk --components=sys-img-armeabi-v7a-android-24
                             --accept-licenses='android-sdk-license-[0-9a-f]{8}'
                             --no-ui
      before_script:
        - echo no | android create avd
          --force
          --name test
          --target android-24
          --abi armeabi-v7a
        - emulator
          -avd test
          -memory 1024
          -no-skin -no-audio -no-window &

        - android-wait-for-emulator
        - adb shell settings put global window_animation_scale 0 &
        - adb shell settings put global transition_animation_scale 0 &
        - adb shell settings put global animator_duration_scale 0 &
        - sleep 10
        - adb shell input keyevent 82 &
      script:         ./gradlew connectedAndroidTest

# ------------------------- ------------------------- ------------------------- #

after_success: ./script/discord.sh success $WEBHOOK_URL
after_failure: ./script/discord.sh failure $WEBHOOK_URL
after_script:
  - cat ${TRAVIS_BUILD_DIR}/*/build/outputs/androidTest-results/connected/*
  - cat ${TRAVIS_BUILD_DIR}/*/build/reports/lint-results.xml